### ISSUE TITLE
Add option for ESLint / Prettier config

### ISSUE THREAD

**Issue by dvalinotti** [litelement-dev/create-lit#3]
Would like to add a multi-select option to the CLI that allows users to select some options for their starter project, starting with an ESLint Prettier config added to their project. 

Other things we could add to the multi-select later on would be stylesheets separate from the component TS code, using NPM or Yarn, or Unit testing 😀. Will be working on this issue today.

**Comment by dvalinotti** [comment]
#4

**Comment by herberthobregon** [comment]
Let me test the pull request #4 on my local machine to do the merge 🚀🔥
